# Generated by Django 3.0.5 on 2023-04-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admin',
        ),
    ]
